# Generated by Django 5.0.6 on 2024-05-24 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_lot_no_remove_selected_thickness_selected_point_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lot_no',
            new_name='LotNo',
        ),
        migrations.CreateModel(
            name='LottData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=100, unique=True)),
                ('weight', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=100)),
                ('sheet', models.CharField(max_length=20)),
                ('flag', models.CharField(max_length=50)),
                ('total_weight', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('remarks', models.CharField(max_length=20)),
                ('lot_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lotno')),
                ('point', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.point')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quality')),
            ],
        ),
        migrations.DeleteModel(
            name='lottdataa',
        ),
    ]
