# Generated by Django 5.0.6 on 2024-05-25 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_lot_no_lotno_lottdata_delete_lottdataa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottdata',
            name='lot_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lott',
            name='lot_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lottdata',
            name='date',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lottdata',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.point'),
        ),
        migrations.DeleteModel(
            name='LotNo',
        ),
    ]
