# Generated by Django 3.2.10 on 2024-06-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_dispatchad_dispatch_bill_no_dispatch_bundle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchad',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
