# Generated by Django 3.2.10 on 2024-06-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20240603_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchad',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
