# Generated by Django 3.2.10 on 2024-06-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20240604_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchad',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
