# Generated by Django 3.2.10 on 2024-06-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20240604_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottdata',
            name='point',
        ),
        migrations.RemoveField(
            model_name='lottdata',
            name='quality',
        ),
        migrations.AddField(
            model_name='selected',
            name='bill_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='selected',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Dispatch',
        ),
        migrations.DeleteModel(
            name='Dispatchad',
        ),
        migrations.DeleteModel(
            name='LottData',
        ),
    ]
