# Generated by Django 3.2.10 on 2024-06-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_bundle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='packing',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
