# Generated by Django 3.2.10 on 2024-06-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_bundle_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='packing',
            name='date_packing',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
