# Generated by Django 3.2.10 on 2024-06-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='packing_slip_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
