# Generated by Django 3.2.10 on 2024-06-15 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_packing_slip_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='packing_slip_new',
            name='bundle_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='app.bundle'),
        ),
    ]
