# Generated by Django 3.2.10 on 2024-06-15 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_packing_slip_new_bundle_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packing',
            name='date_packing',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packing_slip_new',
            name='bundle_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packing_slips', to='app.bundle'),
        ),
        migrations.AlterField(
            model_name='selected',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selected',
            name='packing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected', to='app.packing'),
        ),
    ]
