# Generated by Django 3.2.10 on 2024-06-15 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20240615_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selected',
            name='packing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.packing'),
        ),
    ]
