# Generated by Django 3.2.10 on 2024-06-15 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_selected_packing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='packing_slip_new',
            new_name='PackingSlipNew',
        ),
        migrations.RenameField(
            model_name='bundle',
            old_name='bundle_entry',
            new_name='packing',
        ),
        migrations.RenameField(
            model_name='packingslipnew',
            old_name='bundle_entry',
            new_name='bundle',
        ),
    ]
