# Generated by Django 3.2.10 on 2024-06-15 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20240615_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='packing_slip_new',
            name='packing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.packing'),
        ),
    ]
