# Generated by Django 3.2.10 on 2024-06-15 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_packing_slip_new_packing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packing_slip_new',
            name='packing',
        ),
    ]
