# Generated by Django 3.2.10 on 2024-06-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_packing_slip_new_packing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundle',
            old_name='bundle_entry',
            new_name='packing',
        ),
        migrations.AlterField(
            model_name='bundle',
            name='weight',
            field=models.FloatField(),
        ),
    ]
