# Generated by Django 3.2.10 on 2024-06-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20240615_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundle',
            old_name='packing',
            new_name='bundle_entry',
        ),
        migrations.AlterField(
            model_name='bundle',
            name='weight',
            field=models.CharField(max_length=100),
        ),
    ]
